//! Best-effort build metadata so `up --remote` can warn when it would delegate
//! an *unreleased* local build to a login node running the published release of
//! the same version (the version-collision trap: both print `--version` X.Y.Z,
//! but the remote lacks the local tree's unreleased spec fields/flags).
//!
//! Emitted as compile-time env vars consumed via `option_env!`:
//!   - `HPC_COMPOSE_BUILD_DIRTY` = "1" when the tracked working tree has
//!     uncommitted changes at build time, else "0".
//!   - `HPC_COMPOSE_BUILD_REV`   = short git rev, or "" when git is unavailable.
//!   - `docs_search_index.rs` in `OUT_DIR`, generated from `docs/src/*.md`.
//!
//! Everything is best-effort: a release built from a source tarball with no
//! `.git` simply reports clean (`"0"`/`""`), so released users never see the
//! warning. No `rerun-if-changed` is emitted on purpose — that keeps Cargo's
//! default "re-run when any package file changes" behavior, so the dirty flag
//! and embedded docs stay roughly fresh as sources are edited.

use std::{
    collections::BTreeSet,
    env, fs,
    path::{Component, Path, PathBuf},
    process::Command,
};

fn git(args: &[&str]) -> Option<String> {
    let output = Command::new("git").args(args).output().ok()?;
    if !output.status.success() {
        return None;
    }
    Some(String::from_utf8_lossy(&output.stdout).trim().to_string())
}

fn main() {
    let rev = git(&["rev-parse", "--short", "HEAD"]).unwrap_or_default();
    // `--untracked-files=no`: only tracked modifications/staged changes count as
    // "unreleased", so a stray scratch file does not trip the warning.
    let dirty = git(&["status", "--porcelain", "--untracked-files=no"])
        .map(|s| !s.is_empty())
        .unwrap_or(false);

    println!("cargo:rustc-env=HPC_COMPOSE_BUILD_REV={rev}");
    println!(
        "cargo:rustc-env=HPC_COMPOSE_BUILD_DIRTY={}",
        if dirty { "1" } else { "0" }
    );

    let out_dir = PathBuf::from(env::var_os("OUT_DIR").expect("OUT_DIR is set by Cargo"));
    let index = build_docs_search_index(Path::new("docs/src"))
        .unwrap_or_else(|err| panic!("failed to build docs search index: {err}"));
    fs::write(out_dir.join("docs_search_index.rs"), index)
        .expect("write generated docs search index");
}

#[derive(Debug)]
struct DocSource {
    relative_path: String,
    title_hint: Option<String>,
    body: String,
}

#[derive(Debug)]
struct DocSection {
    heading: String,
    body: String,
}

fn build_docs_search_index(docs_dir: &Path) -> Result<String, String> {
    let summary = fs::read_to_string(docs_dir.join("SUMMARY.md"))
        .map_err(|err| format!("read docs/src/SUMMARY.md: {err}"))?;
    let summary_links = summary_links(&summary);

    let mut seen = BTreeSet::new();
    let mut docs = Vec::new();

    for (relative_path, title_hint) in summary_links {
        if !seen.insert(relative_path.clone()) {
            continue;
        }
        let path = docs_dir.join(&relative_path);
        if path.is_file() {
            docs.push(read_doc_source(&path, relative_path, Some(title_hint))?);
        }
    }

    let mut remaining = Vec::new();
    for entry in fs::read_dir(docs_dir).map_err(|err| format!("read docs/src: {err}"))? {
        let entry = entry.map_err(|err| format!("read docs/src entry: {err}"))?;
        let path = entry.path();
        if path.extension().and_then(|ext| ext.to_str()) != Some("md") {
            continue;
        }
        let Some(file_name) = path.file_name().and_then(|name| name.to_str()) else {
            continue;
        };
        if file_name == "SUMMARY.md" || seen.contains(file_name) {
            continue;
        }
        remaining.push(file_name.to_string());
    }
    remaining.sort();

    for relative_path in remaining {
        seen.insert(relative_path.clone());
        docs.push(read_doc_source(
            &docs_dir.join(&relative_path),
            relative_path,
            None,
        )?);
    }

    let mut output = String::new();
    output.push_str("// @generated by build.rs; do not edit by hand.\n");
    output.push_str("const EMBEDDED_DOCS: &[EmbeddedDoc] = &[\n");
    for doc in docs {
        let title = extract_title(&doc.body)
            .or(doc.title_hint)
            .unwrap_or_else(|| title_from_path(&doc.relative_path));
        let sections = extract_sections(&doc.body, &title);
        output.push_str("    EmbeddedDoc {\n");
        output.push_str("        path: ");
        output.push_str(&rust_string_literal(&doc.relative_path));
        output.push_str(",\n        title: ");
        output.push_str(&rust_string_literal(&title));
        output.push_str(",\n        sections: &[\n");
        for section in sections {
            output.push_str("            EmbeddedSection { heading: ");
            output.push_str(&rust_string_literal(&section.heading));
            output.push_str(", body: ");
            output.push_str(&rust_string_literal(&section.body));
            output.push_str(" },\n");
        }
        output.push_str("        ],\n    },\n");
    }
    output.push_str("];\n");
    Ok(output)
}

fn read_doc_source(
    path: &Path,
    relative_path: String,
    title_hint: Option<String>,
) -> Result<DocSource, String> {
    let body = fs::read_to_string(path).map_err(|err| format!("read {}: {err}", path.display()))?;
    Ok(DocSource {
        relative_path,
        title_hint,
        body,
    })
}

fn summary_links(summary: &str) -> Vec<(String, String)> {
    let mut links = Vec::new();
    for line in summary.lines() {
        let line = line.trim_start();
        let Some(label_start) = line.find('[') else {
            continue;
        };
        let Some(label_end) = line[label_start + 1..].find(']') else {
            continue;
        };
        let label_end = label_start + 1 + label_end;
        let label = line[label_start + 1..label_end].trim();
        let rest = &line[label_end + 1..];
        let Some(path_start) = rest.find('(') else {
            continue;
        };
        let Some(path_end) = rest[path_start + 1..].find(')') else {
            continue;
        };
        let raw_path = rest[path_start + 1..path_start + 1 + path_end]
            .split('#')
            .next()
            .unwrap_or("")
            .trim();
        if label.is_empty() {
            continue;
        }
        if let Some(path) = safe_markdown_path(raw_path) {
            links.push((path, label.to_string()));
        }
    }
    links
}

fn safe_markdown_path(raw_path: &str) -> Option<String> {
    let path = Path::new(raw_path);
    if path.extension().and_then(|ext| ext.to_str()) != Some("md") {
        return None;
    }
    if path.components().any(|component| {
        matches!(
            component,
            Component::ParentDir | Component::RootDir | Component::Prefix(_)
        )
    }) {
        return None;
    }
    Some(raw_path.replace('\\', "/"))
}

fn extract_title(markdown: &str) -> Option<String> {
    markdown
        .lines()
        .find_map(markdown_heading)
        .and_then(|(level, heading)| if level == 1 { Some(heading) } else { None })
}

fn extract_sections(markdown: &str, fallback_heading: &str) -> Vec<DocSection> {
    let mut sections = Vec::new();
    let mut current_heading = fallback_heading.to_string();
    let mut current_body = String::new();

    for line in markdown.lines() {
        if let Some((_level, heading)) = markdown_heading(line) {
            push_section(&mut sections, &current_heading, &mut current_body);
            current_heading = heading;
        } else {
            current_body.push_str(line);
            current_body.push('\n');
        }
    }
    push_section(&mut sections, &current_heading, &mut current_body);

    if sections.is_empty() {
        sections.push(DocSection {
            heading: fallback_heading.to_string(),
            body: markdown.to_string(),
        });
    }

    sections
}

fn push_section(sections: &mut Vec<DocSection>, heading: &str, body: &mut String) {
    if sections.is_empty() && body.trim().is_empty() {
        body.clear();
        return;
    }
    if body.trim().is_empty() {
        body.clear();
        return;
    }
    sections.push(DocSection {
        heading: heading.to_string(),
        body: std::mem::take(body),
    });
}

fn markdown_heading(line: &str) -> Option<(usize, String)> {
    let trimmed = line.trim_start();
    let level = trimmed.chars().take_while(|ch| *ch == '#').count();
    if level == 0 || level > 6 {
        return None;
    }
    if !trimmed
        .as_bytes()
        .get(level)
        .is_some_and(u8::is_ascii_whitespace)
    {
        return None;
    }
    let heading = trimmed[level..]
        .trim()
        .trim_end_matches('#')
        .trim()
        .to_string();
    if heading.is_empty() {
        None
    } else {
        Some((level, heading))
    }
}

fn title_from_path(path: &str) -> String {
    let stem = path
        .rsplit('/')
        .next()
        .unwrap_or(path)
        .strip_suffix(".md")
        .unwrap_or(path);
    stem.split(['-', '_'])
        .filter(|part| !part.is_empty())
        .map(|part| {
            let mut chars = part.chars();
            match chars.next() {
                Some(first) => first.to_uppercase().collect::<String>() + chars.as_str(),
                None => String::new(),
            }
        })
        .collect::<Vec<_>>()
        .join(" ")
}

fn rust_string_literal(value: &str) -> String {
    format!("{value:?}")
}
