use std::fmt::Write as _;
use std::path::PathBuf;

use anyhow::Result;

use super::{RenderOptions, render_script_with_options, shell_quote};
use crate::prepare::RuntimePlan;
use crate::tracked_paths;

/// Local launcher render options.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct LocalRenderOptions {
    /// Enables the development control directory consumed by the local supervisor.
    pub dev_reload: bool,
    /// Resolved absolute runtime root (the parent of `<job_id>/`) baked into the
    /// launcher so its `JOB_ROOT` and supervisor directories match the
    /// submission record under an `x-slurm.runtime_root` override. `None` keeps
    /// the default `$SLURM_SUBMIT_DIR/.hpc-compose` layout.
    pub runtime_root: Option<PathBuf>,
}

/// Renders a local launcher script that reuses the normal runtime orchestration.
pub fn render_local_script(plan: &RuntimePlan, job_id: &str, enroot_bin: &str) -> Result<String> {
    render_local_script_with_options(plan, job_id, enroot_bin, &LocalRenderOptions::default())
}

/// Renders a local launcher script with explicit local-supervisor options.
pub fn render_local_script_with_options(
    plan: &RuntimePlan,
    job_id: &str,
    enroot_bin: &str,
    options: &LocalRenderOptions,
) -> Result<String> {
    // Thread the resolved runtime root so the local launcher's baked JOB_ROOT
    // (and the supervisor dirs below) match the submission record exactly,
    // including under an x-slurm.runtime_root override.
    let base = render_script_with_options(
        plan,
        &RenderOptions {
            runtime_root: options.runtime_root.clone(),
            ..RenderOptions::default()
        },
    )?;
    let body = strip_sbatch_directives(&base);
    let mut out = String::new();
    out.push_str("#!/bin/bash\n");
    out.push_str("set -euo pipefail\n");
    out.push_str("# Local launcher generated by hpc-compose\n");
    writeln!(out, "export SLURM_JOB_ID={}", shell_quote(job_id))
        .expect("String write is infallible");
    out.push_str("export SLURM_SUBMIT_DIR=\"${SLURM_SUBMIT_DIR:-$PWD}\"\n");
    out.push_str("export SLURM_JOB_NODELIST=\"127.0.0.1\"\n");
    out.push_str("export SLURMD_NODENAME=\"127.0.0.1\"\n");
    out.push_str("export HOSTNAME=\"127.0.0.1\"\n");
    out.push_str("export HPC_COMPOSE_BACKEND_OVERRIDE=\"local\"\n");
    out.push_str("export HPC_COMPOSE_SLURM_COLLECTOR_ENABLED_OVERRIDE=\"0\"\n");
    out.push_str("export HPC_COMPOSE_SLURM_COLLECTOR_NOTE_OVERRIDE=\"disabled in local mode\"\n");
    writeln!(
        out,
        "export HPC_COMPOSE_LOCAL_ENROOT_BIN={}",
        shell_quote(enroot_bin)
    )
    .expect("String write is infallible");
    // Base of the per-job runtime root, kept in lockstep with the body's baked
    // JOB_ROOT and the submission record so both an x-slurm.runtime_root override
    // and the default layout resolve the supervisor dirs to the tracked location.
    match options.runtime_root.as_deref() {
        Some(runtime_root) => writeln!(
            out,
            "HPC_COMPOSE_LOCAL_JOB_ROOT={}/\"${{SLURM_JOB_ID}}\"",
            shell_quote(&runtime_root.display().to_string())
        ),
        None => writeln!(
            out,
            "HPC_COMPOSE_LOCAL_JOB_ROOT=\"$SLURM_SUBMIT_DIR/{}/${{SLURM_JOB_ID}}\"",
            tracked_paths::METADATA_DIR_NAME
        ),
    }
    .expect("String write is infallible");
    if options.dev_reload {
        out.push_str(
            "export HPC_COMPOSE_DEV_CONTROL_DIR=\"$HPC_COMPOSE_LOCAL_JOB_ROOT/dev-control\"\n",
        );
    }
    out.push_str("HPC_COMPOSE_LOCAL_BIN_DIR=\"$HPC_COMPOSE_LOCAL_JOB_ROOT/.local-bin\"\n");
    out.push_str("mkdir -p \"$HPC_COMPOSE_LOCAL_BIN_DIR\"\n");
    out.push_str("cat > \"$HPC_COMPOSE_LOCAL_BIN_DIR/srun\" <<'HPC_COMPOSE_LOCAL_SRUN'\n");
    out.push_str(render_local_srun_shim());
    out.push_str("HPC_COMPOSE_LOCAL_SRUN\n");
    out.push_str("chmod +x \"$HPC_COMPOSE_LOCAL_BIN_DIR/srun\"\n");
    out.push_str("export PATH=\"$HPC_COMPOSE_LOCAL_BIN_DIR:$PATH\"\n\n");
    out.push_str(&body);
    Ok(out)
}

fn strip_sbatch_directives(script: &str) -> String {
    let mut out = String::new();
    for (index, line) in script.lines().enumerate() {
        if index == 0 && line.starts_with("#!") {
            continue;
        }
        if line.starts_with("#SBATCH ") {
            continue;
        }
        out.push_str(line);
        out.push('\n');
    }
    out
}

fn render_local_srun_shim() -> &'static str {
    r#"#!/bin/bash
set -euo pipefail
if [[ "${1:-}" == "--help" ]]; then
  echo "usage: srun --container-image=IMAGE"
  exit 0
fi
enroot_bin="${HPC_COMPOSE_LOCAL_ENROOT_BIN:?missing HPC_COMPOSE_LOCAL_ENROOT_BIN}"
container_image=""
container_mounts=""
container_env_names=""
use_entrypoint=0
while (($#)); do
  case "$1" in
    --container-image=*)
      container_image="${1#--container-image=}"
      shift
      ;;
    --container-mounts=*)
      container_mounts="${1#--container-mounts=}"
      shift
      ;;
    --container-env=*)
      container_env_names="${1#--container-env=}"
      shift
      ;;
    --container-entrypoint)
      use_entrypoint=1
      shift
      ;;
    --nodes=*|--ntasks=*|--ntasks-per-node=*|--cpus-per-task=*|--gpus=*|--gres=*|--gpus-per-node=*|--gpus-per-task=*|--cpus-per-gpu=*|--mem-per-gpu=*|--gpu-bind=*|--cpu-bind=*|--mem-bind=*|--distribution=*|--hint=*|--exact|--overlap|--job-name=*|--nodelist=*|--output=*|--error=*|--chdir=*|--task-prolog=*)
      shift
      ;;
    --)
      shift
      break
      ;;
    *)
      break
      ;;
  esac
done
if [[ -z "$container_image" ]]; then
  echo "local srun shim requires --container-image" >&2
  exit 1
fi
declare -a enroot_args=()
declare -a mount_items=()
declare -a env_items=()
if [[ -n "$container_mounts" ]]; then
  IFS=',' read -r -a mount_items <<< "$container_mounts"
  for mount in "${mount_items[@]}"; do
    [[ -z "$mount" ]] && continue
    enroot_args+=(--mount "$mount")
  done
fi
if [[ -n "$container_env_names" ]]; then
  IFS=',' read -r -a env_items <<< "$container_env_names"
  for env_name in "${env_items[@]}"; do
    [[ -z "$env_name" ]] && continue
    if [[ "${!env_name+x}" == "x" ]]; then
      enroot_args+=(--env "$env_name=${!env_name}")
    fi
  done
fi
if (( use_entrypoint )) && (($# == 0)); then
  exec "$enroot_bin" start "${enroot_args[@]}" "$container_image"
fi
exec "$enroot_bin" start "${enroot_args[@]}" "$container_image" "$@"
"#
}
