pub(super) fn render_metrics_helpers(out: &mut String) {
    out.push_str("json_bool_from_flag() {\n");
    out.push_str("  if [[ \"${1:-0}\" == \"1\" ]]; then\n");
    out.push_str("    printf true\n");
    out.push_str("  else\n");
    out.push_str("    printf false\n");
    out.push_str("  fi\n");
    out.push_str("}\n\n");

    out.push_str("metrics_timestamp() {\n");
    out.push_str("  date -u +%Y-%m-%dT%H:%M:%SZ\n");
    out.push_str("}\n\n");

    out.push_str("metrics_warning_once() {\n");
    out.push_str("  local collector=$1\n");
    out.push_str("  local message=$2\n");
    out.push_str("  case \"$collector\" in\n");
    out.push_str("    gpu)\n");
    out.push_str("      [[ \"$GPU_WARNING_EMITTED\" == \"1\" ]] && return 0\n");
    out.push_str("      GPU_WARNING_EMITTED=1\n");
    out.push_str("      ;;\n");
    out.push_str("    slurm)\n");
    out.push_str("      [[ \"$SLURM_WARNING_EMITTED\" == \"1\" ]] && return 0\n");
    out.push_str("      SLURM_WARNING_EMITTED=1\n");
    out.push_str("      ;;\n");
    out.push_str("  esac\n");
    out.push_str("  echo \"metrics warning [$collector]: $message\" >&2\n");
    out.push_str("}\n\n");

    out.push_str("write_metrics_meta() {\n");
    out.push_str("  local tmp_meta=\"$METRICS_META_FILE.tmp\"\n");
    out.push_str("  {\n");
    out.push_str("    printf '{\\n'\n");
    out.push_str(
        "    printf '  \"sampler_pid\": %s,\\n' \"$(json_number_or_null \"$SAMPLER_PID\")\"\n",
    );
    out.push_str("    printf '  \"interval_seconds\": %s,\\n' \"$METRICS_INTERVAL_SECONDS\"\n");
    out.push_str("    printf '  \"collectors\": [\\n'\n");
    out.push_str("    printf '    {\"name\":\"gpu\",\"enabled\":%s,\"available\":%s,\"note\":%s,\"last_sampled_at\":%s},\\n' \\\n");
    out.push_str("      \"$(json_bool_from_flag \"$GPU_COLLECTOR_ENABLED\")\" \\\n");
    out.push_str("      \"$(json_bool_from_flag \"$GPU_COLLECTOR_AVAILABLE\")\" \\\n");
    out.push_str("      \"$(json_string_or_null \"$GPU_COLLECTOR_NOTE\")\" \\\n");
    out.push_str("      \"$(json_string_or_null \"$GPU_COLLECTOR_LAST_SAMPLED_AT\")\"\n");
    out.push_str("    printf '    {\"name\":\"slurm\",\"enabled\":%s,\"available\":%s,\"note\":%s,\"last_sampled_at\":%s}\\n' \\\n");
    out.push_str("      \"$(json_bool_from_flag \"$SLURM_COLLECTOR_ENABLED\")\" \\\n");
    out.push_str("      \"$(json_bool_from_flag \"$SLURM_COLLECTOR_AVAILABLE\")\" \\\n");
    out.push_str("      \"$(json_string_or_null \"$SLURM_COLLECTOR_NOTE\")\" \\\n");
    out.push_str("      \"$(json_string_or_null \"$SLURM_COLLECTOR_LAST_SAMPLED_AT\")\"\n");
    out.push_str("    printf '  ]\\n}\\n'\n");
    out.push_str("  } > \"$tmp_meta\"\n");
    out.push_str("  mv \"$tmp_meta\" \"$METRICS_META_FILE\"\n");
    out.push_str("}\n\n");

    out.push_str("mark_gpu_collector_unavailable() {\n");
    out.push_str("  GPU_COLLECTOR_AVAILABLE=0\n");
    out.push_str("  GPU_COLLECTOR_NOTE=$1\n");
    out.push_str("  write_metrics_meta\n");
    out.push_str("  metrics_warning_once gpu \"$1\"\n");
    out.push_str("}\n\n");

    out.push_str("mark_gpu_collector_success() {\n");
    out.push_str("  GPU_COLLECTOR_AVAILABLE=1\n");
    out.push_str("  GPU_COLLECTOR_NOTE=\"\"\n");
    out.push_str("  GPU_COLLECTOR_LAST_SAMPLED_AT=$1\n");
    out.push_str("  write_metrics_meta\n");
    out.push_str("}\n\n");

    out.push_str("mark_slurm_collector_unavailable() {\n");
    out.push_str("  SLURM_COLLECTOR_AVAILABLE=0\n");
    out.push_str("  SLURM_COLLECTOR_NOTE=$1\n");
    out.push_str("  write_metrics_meta\n");
    out.push_str("  metrics_warning_once slurm \"$1\"\n");
    out.push_str("}\n\n");

    out.push_str("mark_slurm_collector_success() {\n");
    out.push_str("  SLURM_COLLECTOR_AVAILABLE=1\n");
    out.push_str("  SLURM_COLLECTOR_NOTE=\"\"\n");
    out.push_str("  SLURM_COLLECTOR_LAST_SAMPLED_AT=$1\n");
    out.push_str("  write_metrics_meta\n");
    out.push_str("}\n\n");

    out.push_str("sample_gpu_metrics_current_node() {\n");
    out.push_str("  [[ \"$GPU_COLLECTOR_ENABLED\" == \"1\" ]] || return 0\n");
    out.push_str("  if ! command -v nvidia-smi >/dev/null 2>&1; then\n");
    out.push_str(
        "    mark_gpu_collector_unavailable \"nvidia-smi is not available on this node\"\n",
    );
    out.push_str("    return 0\n");
    out.push_str("  fi\n");
    out.push_str("  local sampled_at\n");
    out.push_str("  sampled_at=$(metrics_timestamp)\n");
    out.push_str("  local sample_node=\"${HPC_COMPOSE_GPU_SAMPLE_NODE:-${SLURMD_NODENAME:-${HOSTNAME:-}}}\"\n");
    out.push_str("  local output\n");
    out.push_str("  if ! output=$(nvidia-smi --query-gpu=index,uuid,name,utilization.gpu,utilization.memory,memory.used,memory.total,temperature.gpu,power.draw,power.limit --format=csv,noheader,nounits 2>&1); then\n");
    out.push_str("    mark_gpu_collector_unavailable \"nvidia-smi GPU query failed: $(trim_whitespace \"${output//$'\\n'/; }\")\"\n");
    out.push_str("    return 0\n");
    out.push_str("  fi\n");
    out.push_str("  local line\n");
    out.push_str("  while IFS= read -r line; do\n");
    out.push_str("    [[ -z \"$(trim_whitespace \"$line\")\" ]] && continue\n");
    out.push_str("    IFS=',' read -r raw_index raw_uuid raw_name raw_util_gpu raw_util_mem raw_mem_used raw_mem_total raw_temp raw_power_draw raw_power_limit <<< \"$line\"\n");
    out.push_str("    local index uuid name util_gpu util_mem mem_used mem_total temperature power_draw power_limit\n");
    out.push_str("    index=$(trim_whitespace \"$raw_index\")\n");
    out.push_str("    uuid=$(trim_whitespace \"$raw_uuid\")\n");
    out.push_str("    name=$(trim_whitespace \"$raw_name\")\n");
    out.push_str("    util_gpu=$(trim_whitespace \"$raw_util_gpu\")\n");
    out.push_str("    util_mem=$(trim_whitespace \"$raw_util_mem\")\n");
    out.push_str("    mem_used=$(trim_whitespace \"$raw_mem_used\")\n");
    out.push_str("    mem_total=$(trim_whitespace \"$raw_mem_total\")\n");
    out.push_str("    temperature=$(trim_whitespace \"$raw_temp\")\n");
    out.push_str("    power_draw=$(trim_whitespace \"$raw_power_draw\")\n");
    out.push_str("    power_limit=$(trim_whitespace \"$raw_power_limit\")\n");
    out.push_str("    printf '{\"sampled_at\":\"%s\",\"node\":%s,\"rank\":null,\"local_rank\":null,\"service\":null,\"collector\":\"nvidia-smi\",\"index\":%s,\"uuid\":%s,\"name\":%s,\"utilization_gpu\":%s,\"utilization_memory\":%s,\"memory_used_mib\":%s,\"memory_total_mib\":%s,\"temperature_c\":%s,\"power_draw_w\":%s,\"power_limit_w\":%s}\\n' \\\n");
    out.push_str("      \"$(json_escape \"$sampled_at\")\" \\\n");
    out.push_str("      \"$(json_string_or_null \"$sample_node\")\" \\\n");
    out.push_str("      \"$(json_string_or_null \"$index\")\" \\\n");
    out.push_str("      \"$(json_string_or_null \"$uuid\")\" \\\n");
    out.push_str("      \"$(json_string_or_null \"$name\")\" \\\n");
    out.push_str("      \"$(json_string_or_null \"$util_gpu\")\" \\\n");
    out.push_str("      \"$(json_string_or_null \"$util_mem\")\" \\\n");
    out.push_str("      \"$(json_string_or_null \"$mem_used\")\" \\\n");
    out.push_str("      \"$(json_string_or_null \"$mem_total\")\" \\\n");
    out.push_str("      \"$(json_string_or_null \"$temperature\")\" \\\n");
    out.push_str("      \"$(json_string_or_null \"$power_draw\")\" \\\n");
    out.push_str("      \"$(json_string_or_null \"$power_limit\")\" >> \"$GPU_METRICS_FILE\"\n");
    out.push_str("  done <<< \"$output\"\n");
    out.push_str("  local process_output\n");
    out.push_str("  if process_output=$(nvidia-smi --query-compute-apps=gpu_uuid,pid,process_name,used_gpu_memory --format=csv,noheader,nounits 2>&1); then\n");
    out.push_str("    while IFS= read -r line; do\n");
    out.push_str("      [[ -z \"$(trim_whitespace \"$line\")\" ]] && continue\n");
    out.push_str("      IFS=',' read -r raw_gpu_uuid raw_pid raw_process_name raw_used_memory <<< \"$line\"\n");
    out.push_str("      local gpu_uuid pid process_name used_memory\n");
    out.push_str("      gpu_uuid=$(trim_whitespace \"$raw_gpu_uuid\")\n");
    out.push_str("      pid=$(trim_whitespace \"$raw_pid\")\n");
    out.push_str("      process_name=$(trim_whitespace \"$raw_process_name\")\n");
    out.push_str("      used_memory=$(trim_whitespace \"$raw_used_memory\")\n");
    out.push_str("      printf '{\"sampled_at\":\"%s\",\"node\":%s,\"rank\":null,\"local_rank\":null,\"service\":null,\"collector\":\"nvidia-smi\",\"gpu_uuid\":%s,\"pid\":%s,\"process_name\":%s,\"used_memory_mib\":%s}\\n' \\\n");
    out.push_str("        \"$(json_escape \"$sampled_at\")\" \\\n");
    out.push_str("        \"$(json_string_or_null \"$sample_node\")\" \\\n");
    out.push_str("        \"$(json_string_or_null \"$gpu_uuid\")\" \\\n");
    out.push_str("        \"$(json_string_or_null \"$pid\")\" \\\n");
    out.push_str("        \"$(json_string_or_null \"$process_name\")\" \\\n");
    out.push_str(
        "        \"$(json_string_or_null \"$used_memory\")\" >> \"$GPU_PROCESSES_FILE\"\n",
    );
    out.push_str("    done <<< \"$process_output\"\n");
    out.push_str("  else\n");
    out.push_str("    GPU_COLLECTOR_AVAILABLE=1\n");
    out.push_str("    GPU_COLLECTOR_NOTE=\"nvidia-smi compute process query failed: $(trim_whitespace \"${process_output//$'\\n'/; }\")\"\n");
    out.push_str("    GPU_COLLECTOR_LAST_SAMPLED_AT=$sampled_at\n");
    out.push_str("    write_metrics_meta\n");
    out.push_str("    metrics_warning_once gpu \"$GPU_COLLECTOR_NOTE\"\n");
    out.push_str("    return 0\n");
    out.push_str("  fi\n");
    out.push_str("  mark_gpu_collector_success \"$sampled_at\"\n");
    out.push_str("}\n\n");

    out.push_str("write_gpu_sample_node_script() {\n");
    out.push_str("  local script_path=\"$METRICS_DIR/gpu-sample-node.sh\"\n");
    out.push_str("  cat > \"$script_path\" <<'HPC_COMPOSE_GPU_SAMPLE_NODE'\n");
    out.push_str("#!/bin/bash\n");
    out.push_str("set -euo pipefail\n");
    out.push_str("sampled_at=$1\n");
    out.push_str("output_root=$2\n");
    out.push_str("node=\"${SLURMD_NODENAME:-${HOSTNAME:-}}\"\n");
    out.push_str("if [[ -z \"$node\" ]]; then node=$(hostname); fi\n");
    out.push_str("node_dir=\"$output_root/$node\"\n");
    out.push_str("mkdir -p \"$node_dir\"\n");
    out.push_str("json_escape() {\n");
    out.push_str("  local value=$1\n");
    out.push_str("  value=${value//\\\\/\\\\\\\\}\n");
    out.push_str("  value=${value//\\\"/\\\\\\\"}\n");
    out.push_str("  value=${value//$'\\n'/\\\\n}\n");
    out.push_str("  value=${value//$'\\r'/\\\\r}\n");
    out.push_str("  value=${value//$'\\t'/\\\\t}\n");
    out.push_str("  printf '%s' \"$value\"\n");
    out.push_str("}\n");
    out.push_str("json_string_or_null() {\n");
    out.push_str("  local value=${1-}\n");
    out.push_str("  if [[ -z \"$value\" ]]; then printf null; else printf '\"%s\"' \"$(json_escape \"$value\")\"; fi\n");
    out.push_str("}\n");
    out.push_str("trim_whitespace() {\n");
    out.push_str("  local value=${1-}\n");
    out.push_str("  value=${value#\"${value%%[![:space:]]*}\"}\n");
    out.push_str("  value=${value%\"${value##*[![:space:]]}\"}\n");
    out.push_str("  printf '%s' \"$value\"\n");
    out.push_str("}\n");
    out.push_str("if ! command -v nvidia-smi >/dev/null 2>&1; then\n");
    out.push_str(
        "  printf 'nvidia-smi unavailable on %s\\n' \"$node\" > \"$node_dir/status.txt\"\n",
    );
    out.push_str("  exit 0\n");
    out.push_str("fi\n");
    out.push_str("output=\"\"\n");
    out.push_str("if output=$(nvidia-smi --query-gpu=index,uuid,name,utilization.gpu,utilization.memory,memory.used,memory.total,temperature.gpu,power.draw,power.limit --format=csv,noheader,nounits 2>&1); then\n");
    out.push_str("  while IFS= read -r line; do\n");
    out.push_str("    [[ -z \"$(trim_whitespace \"$line\")\" ]] && continue\n");
    out.push_str("    IFS=',' read -r raw_index raw_uuid raw_name raw_util_gpu raw_util_mem raw_mem_used raw_mem_total raw_temp raw_power_draw raw_power_limit <<< \"$line\"\n");
    out.push_str("    index=$(trim_whitespace \"$raw_index\")\n");
    out.push_str("    uuid=$(trim_whitespace \"$raw_uuid\")\n");
    out.push_str("    name=$(trim_whitespace \"$raw_name\")\n");
    out.push_str("    util_gpu=$(trim_whitespace \"$raw_util_gpu\")\n");
    out.push_str("    util_mem=$(trim_whitespace \"$raw_util_mem\")\n");
    out.push_str("    mem_used=$(trim_whitespace \"$raw_mem_used\")\n");
    out.push_str("    mem_total=$(trim_whitespace \"$raw_mem_total\")\n");
    out.push_str("    temperature=$(trim_whitespace \"$raw_temp\")\n");
    out.push_str("    power_draw=$(trim_whitespace \"$raw_power_draw\")\n");
    out.push_str("    power_limit=$(trim_whitespace \"$raw_power_limit\")\n");
    out.push_str("    printf '{\"sampled_at\":\"%s\",\"node\":%s,\"rank\":null,\"local_rank\":null,\"service\":null,\"collector\":\"nvidia-smi\",\"index\":%s,\"uuid\":%s,\"name\":%s,\"utilization_gpu\":%s,\"utilization_memory\":%s,\"memory_used_mib\":%s,\"memory_total_mib\":%s,\"temperature_c\":%s,\"power_draw_w\":%s,\"power_limit_w\":%s}\\n' \\\n");
    out.push_str("      \"$(json_escape \"$sampled_at\")\" \"$(json_string_or_null \"$node\")\" \"$(json_string_or_null \"$index\")\" \"$(json_string_or_null \"$uuid\")\" \"$(json_string_or_null \"$name\")\" \"$(json_string_or_null \"$util_gpu\")\" \"$(json_string_or_null \"$util_mem\")\" \"$(json_string_or_null \"$mem_used\")\" \"$(json_string_or_null \"$mem_total\")\" \"$(json_string_or_null \"$temperature\")\" \"$(json_string_or_null \"$power_draw\")\" \"$(json_string_or_null \"$power_limit\")\" >> \"$node_dir/gpu.jsonl\"\n");
    out.push_str("  done <<< \"$output\"\n");
    out.push_str("else\n");
    out.push_str("  printf 'nvidia-smi GPU query failed on %s: %s\\n' \"$node\" \"$(trim_whitespace \"${output//$'\\n'/; }\")\" > \"$node_dir/status.txt\"\n");
    out.push_str("fi\n");
    out.push_str("process_output=\"\"\n");
    out.push_str("if process_output=$(nvidia-smi --query-compute-apps=gpu_uuid,pid,process_name,used_gpu_memory --format=csv,noheader,nounits 2>&1); then\n");
    out.push_str("  while IFS= read -r line; do\n");
    out.push_str("    [[ -z \"$(trim_whitespace \"$line\")\" ]] && continue\n");
    out.push_str(
        "    IFS=',' read -r raw_gpu_uuid raw_pid raw_process_name raw_used_memory <<< \"$line\"\n",
    );
    out.push_str("    gpu_uuid=$(trim_whitespace \"$raw_gpu_uuid\")\n");
    out.push_str("    pid=$(trim_whitespace \"$raw_pid\")\n");
    out.push_str("    process_name=$(trim_whitespace \"$raw_process_name\")\n");
    out.push_str("    used_memory=$(trim_whitespace \"$raw_used_memory\")\n");
    out.push_str("    printf '{\"sampled_at\":\"%s\",\"node\":%s,\"rank\":null,\"local_rank\":null,\"service\":null,\"collector\":\"nvidia-smi\",\"gpu_uuid\":%s,\"pid\":%s,\"process_name\":%s,\"used_memory_mib\":%s}\\n' \\\n");
    out.push_str("      \"$(json_escape \"$sampled_at\")\" \"$(json_string_or_null \"$node\")\" \"$(json_string_or_null \"$gpu_uuid\")\" \"$(json_string_or_null \"$pid\")\" \"$(json_string_or_null \"$process_name\")\" \"$(json_string_or_null \"$used_memory\")\" >> \"$node_dir/gpu_processes.jsonl\"\n");
    out.push_str("  done <<< \"$process_output\"\n");
    out.push_str("fi\n");
    out.push_str("HPC_COMPOSE_GPU_SAMPLE_NODE\n");
    out.push_str("  chmod +x \"$script_path\"\n");
    out.push_str("  printf '%s' \"$script_path\"\n");
    out.push_str("}\n\n");

    out.push_str("sample_gpu_metrics_all_nodes() {\n");
    out.push_str("  [[ \"$GPU_COLLECTOR_ENABLED\" == \"1\" ]] || return 0\n");
    out.push_str("  local sampled_at\n");
    out.push_str("  sampled_at=$(metrics_timestamp)\n");
    out.push_str("  local sample_root=\"$METRICS_DIR/gpu-node-samples/$sampled_at\"\n");
    out.push_str("  rm -rf \"$sample_root\"\n");
    out.push_str("  mkdir -p \"$sample_root\"\n");
    out.push_str("  local script_path\n");
    out.push_str("  script_path=$(write_gpu_sample_node_script)\n");
    out.push_str("  if ! srun --nodes=\"$HPC_COMPOSE_NODE_COUNT\" --ntasks=\"$HPC_COMPOSE_NODE_COUNT\" --ntasks-per-node=1 --exact --overlap bash \"$script_path\" \"$sampled_at\" \"$sample_root\" >/dev/null 2>&1; then\n");
    out.push_str(
        "    mark_gpu_collector_unavailable \"all-node nvidia-smi sampling failed through srun\"\n",
    );
    out.push_str("    return 0\n");
    out.push_str("  fi\n");
    out.push_str("  shopt -s nullglob\n");
    out.push_str("  local gpu_files=(\"$sample_root\"/*/gpu.jsonl)\n");
    out.push_str("  local proc_files=(\"$sample_root\"/*/gpu_processes.jsonl)\n");
    out.push_str("  local status_files=(\"$sample_root\"/*/status.txt)\n");
    out.push_str("  if (( ${#gpu_files[@]} == 0 )); then\n");
    out.push_str("    mark_gpu_collector_unavailable \"nvidia-smi produced no GPU samples on allocation nodes\"\n");
    out.push_str("    return 0\n");
    out.push_str("  fi\n");
    out.push_str("  cat \"${gpu_files[@]}\" >> \"$GPU_METRICS_FILE\"\n");
    out.push_str("  if (( ${#proc_files[@]} > 0 )); then cat \"${proc_files[@]}\" >> \"$GPU_PROCESSES_FILE\"; fi\n");
    out.push_str("  if (( ${#status_files[@]} > 0 )); then GPU_COLLECTOR_NOTE=\"$(paste -sd '; ' \"${status_files[@]}\" 2>/dev/null || true)\"; fi\n");
    out.push_str("  mark_gpu_collector_success \"$sampled_at\"\n");
    out.push_str("}\n\n");

    out.push_str("sample_gpu_metrics() {\n");
    out.push_str("  if [[ \"${BACKEND:-slurm}\" == \"slurm\" && \"${HPC_COMPOSE_NODE_COUNT:-1}\" -gt 1 ]]; then\n");
    out.push_str("    sample_gpu_metrics_all_nodes\n");
    out.push_str("  else\n");
    out.push_str("    sample_gpu_metrics_current_node\n");
    out.push_str("  fi\n");
    out.push_str("}\n\n");

    out.push_str("sample_slurm_metrics() {\n");
    out.push_str("  [[ \"$SLURM_COLLECTOR_ENABLED\" == \"1\" ]] || return 0\n");
    out.push_str("  if ! command -v sstat >/dev/null 2>&1; then\n");
    out.push_str("    mark_slurm_collector_unavailable \"sstat is not available on this node\"\n");
    out.push_str("    return 0\n");
    out.push_str("  fi\n");
    out.push_str("  local sampled_at\n");
    out.push_str("  sampled_at=$(metrics_timestamp)\n");
    out.push_str("  local output\n");
    out.push_str("  if ! output=$(sstat --allsteps --jobs \"$SLURM_JOB_ID\" --parsable2 --noconvert --format=JobID,NTasks,AveCPU,AveRSS,MaxRSS,AllocTRES,TRESUsageInAve 2>&1); then\n");
    out.push_str("    mark_slurm_collector_unavailable \"sstat query failed: $(trim_whitespace \"${output//$'\\n'/; }\")\"\n");
    out.push_str("    return 0\n");
    out.push_str("  fi\n");
    out.push_str("  local line\n");
    out.push_str("  while IFS= read -r line; do\n");
    out.push_str("    [[ -z \"$(trim_whitespace \"$line\")\" ]] && continue\n");
    out.push_str("    [[ \"$line\" == JobID* ]] && continue\n");
    out.push_str("    local -a fields=()\n");
    out.push_str("    IFS='|' read -r -a fields <<< \"$line\"\n");
    out.push_str("    if (( ${#fields[@]} != 7 )); then\n");
    out.push_str("      mark_slurm_collector_unavailable \"malformed sstat output while sampling metrics\"\n");
    out.push_str("      return 0\n");
    out.push_str("    fi\n");
    out.push_str("    local step_id\n");
    out.push_str("    step_id=$(trim_whitespace \"${fields[0]}\")\n");
    out.push_str("    if [[ ! \"$step_id\" =~ ^${SLURM_JOB_ID}\\.[0-9]+$ ]]; then\n");
    out.push_str("      continue\n");
    out.push_str("    fi\n");
    out.push_str("    local ntasks ave_cpu ave_rss max_rss alloc_tres tres_usage_in_ave\n");
    out.push_str("    ntasks=$(trim_whitespace \"${fields[1]}\")\n");
    out.push_str("    ave_cpu=$(trim_whitespace \"${fields[2]}\")\n");
    out.push_str("    ave_rss=$(trim_whitespace \"${fields[3]}\")\n");
    out.push_str("    max_rss=$(trim_whitespace \"${fields[4]}\")\n");
    out.push_str("    alloc_tres=$(trim_whitespace \"${fields[5]}\")\n");
    out.push_str("    tres_usage_in_ave=$(trim_whitespace \"${fields[6]}\")\n");
    out.push_str("    printf '{\"sampled_at\":\"%s\",\"step_id\":%s,\"ntasks\":%s,\"ave_cpu\":%s,\"ave_rss\":%s,\"max_rss\":%s,\"alloc_tres\":%s,\"tres_usage_in_ave\":%s}\\n' \\\n");
    out.push_str("      \"$(json_escape \"$sampled_at\")\" \\\n");
    out.push_str("      \"$(json_string_or_null \"$step_id\")\" \\\n");
    out.push_str("      \"$(json_string_or_null \"$ntasks\")\" \\\n");
    out.push_str("      \"$(json_string_or_null \"$ave_cpu\")\" \\\n");
    out.push_str("      \"$(json_string_or_null \"$ave_rss\")\" \\\n");
    out.push_str("      \"$(json_string_or_null \"$max_rss\")\" \\\n");
    out.push_str("      \"$(json_string_or_null \"$alloc_tres\")\" \\\n");
    out.push_str(
        "      \"$(json_string_or_null \"$tres_usage_in_ave\")\" >> \"$SLURM_METRICS_FILE\"\n",
    );
    out.push_str("  done <<< \"$output\"\n");
    out.push_str("  mark_slurm_collector_success \"$sampled_at\"\n");
    out.push_str("}\n\n");

    out.push_str("write_metrics_diagnostics_node_script() {\n");
    out.push_str("  local script_path=\"$METRICS_DIR/diagnostics-node.sh\"\n");
    out.push_str("  cat > \"$script_path\" <<'HPC_COMPOSE_DIAGNOSTICS_NODE'\n");
    out.push_str("#!/bin/bash\n");
    out.push_str("set -euo pipefail\n");
    out.push_str("root=$1\n");
    out.push_str("node=\"${SLURMD_NODENAME:-${HOSTNAME:-}}\"\n");
    out.push_str("if [[ -z \"$node\" ]]; then node=$(hostname); fi\n");
    out.push_str("dir=\"$root/nodes/$node\"\n");
    out.push_str("mkdir -p \"$dir\"\n");
    out.push_str("env | sort | grep -E '^(NCCL|UCX|FI|CUDA|ROCR|HIP|OMPI|PMI|PMIX|I_MPI)_' > \"$dir/env.txt\" 2>/dev/null || true\n");
    out.push_str("if command -v nvidia-smi >/dev/null 2>&1; then nvidia-smi topo -m > \"$dir/nvidia-smi-topo.txt\" 2>&1 || true; nvidia-smi -q > \"$dir/nvidia-smi-q.txt\" 2>&1 || true; fi\n");
    out.push_str("if command -v ibstat >/dev/null 2>&1; then ibstat > \"$dir/ibstat.txt\" 2>&1 || true; fi\n");
    out.push_str("if command -v ibv_devinfo >/dev/null 2>&1; then ibv_devinfo > \"$dir/ibv_devinfo.txt\" 2>&1 || true; fi\n");
    out.push_str("if command -v ucx_info >/dev/null 2>&1; then ucx_info -v > \"$dir/ucx_info.txt\" 2>&1 || true; fi\n");
    out.push_str("if command -v fi_info >/dev/null 2>&1; then fi_info > \"$dir/fi_info.txt\" 2>&1 || true; fi\n");
    out.push_str("HPC_COMPOSE_DIAGNOSTICS_NODE\n");
    out.push_str("  chmod +x \"$script_path\"\n");
    out.push_str("  printf '%s' \"$script_path\"\n");
    out.push_str("}\n\n");

    out.push_str("capture_metrics_diagnostics() {\n");
    out.push_str("  mkdir -p \"$METRICS_DIAGNOSTICS_DIR\"\n");
    out.push_str("  local script_path\n");
    out.push_str("  script_path=$(write_metrics_diagnostics_node_script)\n");
    out.push_str("  if [[ \"${BACKEND:-slurm}\" == \"slurm\" && \"${HPC_COMPOSE_NODE_COUNT:-1}\" -gt 1 ]]; then\n");
    out.push_str("    srun --nodes=\"$HPC_COMPOSE_NODE_COUNT\" --ntasks=\"$HPC_COMPOSE_NODE_COUNT\" --ntasks-per-node=1 --exact --overlap bash \"$script_path\" \"$METRICS_DIAGNOSTICS_DIR\" >/dev/null 2>&1 || true\n");
    out.push_str("  else\n");
    out.push_str(
        "    bash \"$script_path\" \"$METRICS_DIAGNOSTICS_DIR\" >/dev/null 2>&1 || true\n",
    );
    out.push_str("  fi\n");
    out.push_str("}\n\n");

    out.push_str("sample_metrics_once() {\n");
    out.push_str("  sample_gpu_metrics\n");
    out.push_str("  sample_slurm_metrics\n");
    out.push_str("}\n\n");

    out.push_str("metrics_sampler_loop() {\n");
    out.push_str("  while true; do\n");
    out.push_str("    sleep \"$METRICS_INTERVAL_SECONDS\"\n");
    out.push_str("    sample_metrics_once\n");
    out.push_str("  done\n");
    out.push_str("}\n\n");

    out.push_str("start_metrics_sampler() {\n");
    out.push_str("  mkdir -p \"$METRICS_DIR\"\n");
    out.push_str("  : > \"$GPU_METRICS_FILE\"\n");
    out.push_str("  : > \"$GPU_PROCESSES_FILE\"\n");
    out.push_str("  : > \"$SLURM_METRICS_FILE\"\n");
    out.push_str("  capture_metrics_diagnostics\n");
    out.push_str("  write_metrics_meta\n");
    out.push_str("  sample_metrics_once\n");
    out.push_str("  metrics_sampler_loop &\n");
    out.push_str("  SAMPLER_PID=$!\n");
    out.push_str("  write_metrics_meta\n");
    out.push_str("}\n\n");

    out.push_str("stop_metrics_sampler() {\n");
    out.push_str("  [[ -n \"$SAMPLER_PID\" ]] || return 0\n");
    out.push_str("  if kill -0 \"$SAMPLER_PID\" 2>/dev/null; then\n");
    out.push_str("    kill \"$SAMPLER_PID\" 2>/dev/null || true\n");
    out.push_str("    wait \"$SAMPLER_PID\" 2>/dev/null || true\n");
    out.push_str("  fi\n");
    out.push_str("}\n\n");
}
