//! Unified cleanup planning for tracked jobs plus shared-cache residue.

use std::collections::BTreeSet;
use std::time::UNIX_EPOCH;

use crate::context::repo_root_or_cwd;

use super::*;

const SECONDS_PER_DAY: u64 = 86_400;

/// Extra cleanup details included by `clean --deep`.
#[allow(missing_docs)]
#[derive(Debug, Clone, Serialize, schemars::JsonSchema)]
pub struct DeepCleanupDetails {
    pub cache_dir: PathBuf,
    pub rendezvous: crate::rendezvous::RendezvousPruneReport,
    pub orphan_runtime_dirs: Vec<OrphanRuntimeDirReport>,
}

/// One per-job enroot runtime directory found under `cache_dir/runtime/`.
#[allow(missing_docs)]
#[derive(Debug, Clone, Serialize, schemars::JsonSchema)]
pub struct OrphanRuntimeDirReport {
    pub job_id: String,
    pub path: PathBuf,
    pub selected: bool,
    pub reason: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub modified_at: Option<u64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub bytes_reclaimed: Option<u64>,
}

/// Builds a unified cleanup report without deleting anything.
///
/// The base tracked-job fields match [`build_cleanup_report`]. The optional
/// `deep` section adds expired rendezvous records and orphaned per-job enroot
/// runtime directories, but never broadens into content-addressed cache
/// artifacts.
pub fn build_deep_cleanup_report(
    spec_path: &Path,
    cache_dir: &Path,
    mode: CleanupMode,
    include_disk_usage: bool,
    dry_run: bool,
) -> Result<CleanupReport> {
    let mut report = build_cleanup_report(spec_path, mode, include_disk_usage, dry_run)?;
    let now = scheduler::unix_timestamp_now();
    let rendezvous = crate::rendezvous::build_prune_report(cache_dir, now)?;
    let protected_job_ids = protected_runtime_job_ids(spec_path, cache_dir, include_disk_usage)?;
    let orphan_runtime_dirs = build_orphan_runtime_dir_report(
        cache_dir,
        &report,
        &protected_job_ids,
        mode,
        include_disk_usage,
        now,
    )?;
    if include_disk_usage {
        let tracked_bytes = report.total_bytes_reclaimed.unwrap_or(0);
        let rendezvous_bytes = size_of_files(&rendezvous.removed)?;
        let orphan_bytes = orphan_runtime_dirs
            .iter()
            .filter(|entry| entry.selected)
            .filter_map(|entry| entry.bytes_reclaimed)
            .fold(0_u64, u64::saturating_add);
        report.total_bytes_reclaimed = Some(
            tracked_bytes
                .saturating_add(rendezvous_bytes)
                .saturating_add(orphan_bytes),
        );
    }
    report.deep = Some(DeepCleanupDetails {
        cache_dir: cache_dir.to_path_buf(),
        rendezvous,
        orphan_runtime_dirs,
    });
    Ok(report)
}

/// Executes a unified cleanup report generated by [`build_deep_cleanup_report`].
///
/// Missing paths are tolerated so a report remains safe to execute after a
/// dry-run inspection or a concurrent teardown.
pub fn run_deep_cleanup_report(report: &CleanupReport) -> Result<()> {
    run_cleanup_report(report)?;
    if let Some(deep) = &report.deep {
        crate::rendezvous::run_prune_report(&deep.rendezvous)?;
        for entry in deep
            .orphan_runtime_dirs
            .iter()
            .filter(|entry| entry.selected)
        {
            remove_path_if_present(&entry.path)?;
        }
    }
    Ok(())
}

fn build_orphan_runtime_dir_report(
    cache_dir: &Path,
    cleanup_report: &CleanupReport,
    protected_job_ids: &BTreeSet<String>,
    mode: CleanupMode,
    include_disk_usage: bool,
    now: u64,
) -> Result<Vec<OrphanRuntimeDirReport>> {
    let runtime_root = cache_dir.join(tracked_paths::ENROOT_RUNTIME_DIR_NAME);
    if !runtime_root.is_dir() {
        return Ok(Vec::new());
    }
    let referenced_job_ids = cleanup_report
        .jobs
        .iter()
        .map(|job| job.inventory.job_id.clone())
        .chain(protected_job_ids.iter().cloned())
        .collect::<BTreeSet<_>>();
    let cutoff = match mode {
        CleanupMode::Age { age_days } => {
            Some(now.saturating_sub(age_days.saturating_mul(SECONDS_PER_DAY)))
        }
        CleanupMode::AllExceptLatest => None,
    };

    let mut entries = Vec::new();
    for entry in fs::read_dir(&runtime_root)
        .with_context(|| format!("failed to read {}", runtime_root.display()))?
    {
        let entry = entry?;
        let path = entry.path();
        if !entry
            .file_type()
            .with_context(|| format!("failed to stat {}", path.display()))?
            .is_dir()
        {
            continue;
        }
        let Some(job_id) = path.file_name().and_then(|name| name.to_str()) else {
            continue;
        };
        if referenced_job_ids.contains(job_id) {
            continue;
        }
        let modified_at = modified_unix_seconds(&path);
        let selected = match cutoff {
            Some(cutoff) => modified_at.is_none_or(|modified| modified < cutoff),
            None => true,
        };
        let reason = if selected {
            "unreferenced per-job enroot runtime dir".to_string()
        } else {
            "unreferenced per-job enroot runtime dir newer than age cutoff".to_string()
        };
        let bytes_reclaimed = if selected && include_disk_usage {
            Some(size_of_path(&path)?)
        } else {
            None
        };
        entries.push(OrphanRuntimeDirReport {
            job_id: job_id.to_string(),
            path,
            selected,
            reason,
            modified_at,
            bytes_reclaimed,
        });
    }
    entries.sort_by(|left, right| left.job_id.cmp(&right.job_id));
    Ok(entries)
}

fn protected_runtime_job_ids(
    spec_path: &Path,
    cache_dir: &Path,
    include_disk_usage: bool,
) -> Result<BTreeSet<String>> {
    let compose_file = absolute_path(spec_path)?;
    let scan_root = repo_root_or_cwd(compose_file.parent().unwrap_or_else(|| Path::new(".")));
    let mut protected = BTreeSet::new();
    let inventory = record::scan_job_inventory_from_root(&scan_root, include_disk_usage)?;
    for entry in inventory.jobs.into_iter().filter(|entry| {
        entry.runtime_cache_dir == tracked_paths::enroot_runtime_job_dir(cache_dir, &entry.job_id)
    }) {
        protected.insert(entry.job_id);
    }
    collect_job_record_stems(&scan_root, &mut protected)?;
    Ok(protected)
}

fn collect_job_record_stems(root: &Path, protected: &mut BTreeSet<String>) -> Result<()> {
    if !root.is_dir() {
        return Ok(());
    }
    let entries = match fs::read_dir(root) {
        Ok(entries) => entries,
        Err(err) if err.kind() == io::ErrorKind::NotFound => return Ok(()),
        Err(err) => return Err(err).context(format!("failed to read {}", root.display())),
    };
    for entry in entries {
        let entry = entry?;
        let path = entry.path();
        let file_type = entry
            .file_type()
            .with_context(|| format!("failed to stat {}", path.display()))?;
        if !file_type.is_dir() {
            continue;
        }
        let name = entry.file_name();
        let name = name.to_string_lossy();
        if name == tracked_paths::METADATA_DIR_NAME {
            collect_job_ids_from_jobs_dir(&path.join(tracked_paths::JOBS_DIR_NAME), protected)?;
            continue;
        }
        if matches!(
            name.as_ref(),
            ".git"
                | ".hg"
                | ".svn"
                | ".mypy_cache"
                | ".pytest_cache"
                | ".ruff_cache"
                | ".tox"
                | ".venv"
                | "target"
                | "node_modules"
                | "__pycache__"
                | "venv"
        ) {
            continue;
        }
        collect_job_record_stems(&path, protected)?;
    }
    Ok(())
}

fn collect_job_ids_from_jobs_dir(jobs_dir: &Path, protected: &mut BTreeSet<String>) -> Result<()> {
    if !jobs_dir.is_dir() {
        return Ok(());
    }
    for entry in
        fs::read_dir(jobs_dir).with_context(|| format!("failed to read {}", jobs_dir.display()))?
    {
        let entry = entry?;
        let path = entry.path();
        if path.extension().and_then(|ext| ext.to_str()) != Some("json") {
            continue;
        }
        if let Some(job_id) = path.file_stem().and_then(|stem| stem.to_str())
            && !job_id.trim().is_empty()
        {
            protected.insert(job_id.to_string());
        }
    }
    Ok(())
}

fn modified_unix_seconds(path: &Path) -> Option<u64> {
    fs::metadata(path)
        .ok()
        .and_then(|metadata| metadata.modified().ok())
        .and_then(|modified| modified.duration_since(UNIX_EPOCH).ok())
        .map(|duration| duration.as_secs())
}

fn size_of_files(paths: &[PathBuf]) -> Result<u64> {
    paths.iter().try_fold(0_u64, |total, path| {
        let bytes = match fs::metadata(path) {
            Ok(metadata) if metadata.is_file() => metadata.len(),
            Ok(metadata) if metadata.is_dir() => size_of_path(path)?,
            Ok(_) | Err(_) => 0,
        };
        Ok(total.saturating_add(bytes))
    })
}

fn size_of_path(path: &Path) -> Result<u64> {
    let metadata = match fs::metadata(path) {
        Ok(metadata) => metadata,
        Err(err) if err.kind() == io::ErrorKind::NotFound => return Ok(0),
        Err(err) => {
            return Err(err).with_context(|| format!("failed to stat {}", path.display()));
        }
    };
    if metadata.is_file() {
        return Ok(metadata.len());
    }
    if !metadata.is_dir() {
        return Ok(0);
    }

    let mut total = 0_u64;
    for entry in fs::read_dir(path).with_context(|| format!("failed to read {}", path.display()))? {
        let entry = entry?;
        total = total.saturating_add(size_of_path(&entry.path())?);
    }
    Ok(total)
}

fn remove_path_if_present(path: &Path) -> Result<()> {
    let metadata = match fs::symlink_metadata(path) {
        Ok(metadata) => metadata,
        Err(err) if err.kind() == io::ErrorKind::NotFound => return Ok(()),
        Err(err) => {
            return Err(err).with_context(|| format!("failed to stat {}", path.display()));
        }
    };
    if metadata.is_dir() {
        fs::remove_dir_all(path).with_context(|| format!("failed to remove {}", path.display()))
    } else {
        fs::remove_file(path).with_context(|| format!("failed to remove {}", path.display()))
    }
}

#[cfg(test)]
mod tests {
    use tempfile::tempdir;

    use super::*;

    fn write_compose(root: &Path, cache_dir: &Path) -> PathBuf {
        let compose = root.join("compose.yaml");
        fs::write(
            &compose,
            format!(
                "name: deep-clean-test\nx-slurm:\n  cache_dir: {}\nservices:\n  app:\n    image: docker://python:3.12\n    command: ['true']\n",
                cache_dir.display()
            ),
        )
        .expect("write compose");
        compose
    }

    #[test]
    fn deep_report_selects_only_unreferenced_runtime_dirs() {
        let root = tempdir().expect("root");
        let cache = tempdir().expect("cache");
        let compose = write_compose(root.path(), cache.path());
        let spec = crate::spec::ComposeSpec::load(&compose).expect("load spec");
        let plan = crate::planner::build_plan(&compose, spec).expect("build plan");
        let runtime_plan = crate::runtime_plan::build_runtime_plan(&plan);
        let record = build_submission_record(
            &compose,
            root.path(),
            &root.path().join("submit.sbatch"),
            &runtime_plan,
            "12345",
        )
        .expect("record");
        write_submission_record(&record).expect("write record");

        let referenced = tracked_paths::enroot_runtime_job_dir(cache.path(), "12345");
        let orphan = tracked_paths::enroot_runtime_job_dir(cache.path(), "99999");
        fs::create_dir_all(referenced.join("cache")).expect("referenced runtime");
        fs::create_dir_all(orphan.join("cache")).expect("orphan runtime");
        fs::write(orphan.join("cache/blob"), "payload").expect("orphan payload");

        let report = build_deep_cleanup_report(
            &compose,
            cache.path(),
            CleanupMode::AllExceptLatest,
            true,
            true,
        )
        .expect("deep report");
        let deep = report.deep.expect("deep section");
        assert_eq!(deep.orphan_runtime_dirs.len(), 1);
        assert_eq!(deep.orphan_runtime_dirs[0].job_id, "99999");
        assert!(deep.orphan_runtime_dirs[0].selected);
        assert!(
            deep.orphan_runtime_dirs[0]
                .bytes_reclaimed
                .expect("orphan bytes")
                > 0
        );
    }

    #[test]
    fn deep_report_preserves_runtime_dirs_referenced_by_other_compose_contexts() {
        let repo = tempdir().expect("repo");
        fs::create_dir(repo.path().join(".git")).expect("git marker");
        let cache = tempdir().expect("cache");
        let first = repo.path().join("first");
        let second = repo.path().join("second");
        fs::create_dir_all(&first).expect("first dir");
        fs::create_dir_all(&second).expect("second dir");
        let first_compose = write_compose(&first, cache.path());
        let second_compose = write_compose(&second, cache.path());
        let second_spec = crate::spec::ComposeSpec::load(&second_compose).expect("load spec");
        let second_plan =
            crate::planner::build_plan(&second_compose, second_spec).expect("build plan");
        let runtime_plan = crate::runtime_plan::build_runtime_plan(&second_plan);
        let record = build_submission_record(
            &second_compose,
            &second,
            &second.join("submit.sbatch"),
            &runtime_plan,
            "22222",
        )
        .expect("record");
        write_submission_record(&record).expect("write record");

        let referenced_elsewhere = tracked_paths::enroot_runtime_job_dir(cache.path(), "22222");
        let corrupt_record_runtime = tracked_paths::enroot_runtime_job_dir(cache.path(), "33333");
        let orphan = tracked_paths::enroot_runtime_job_dir(cache.path(), "99999");
        fs::create_dir_all(referenced_elsewhere.join("cache")).expect("referenced runtime");
        fs::create_dir_all(corrupt_record_runtime.join("cache")).expect("corrupt runtime");
        fs::create_dir_all(orphan.join("cache")).expect("orphan runtime");
        let corrupt_jobs = second.join(tracked_paths::METADATA_DIR_NAME).join("jobs");
        fs::create_dir_all(&corrupt_jobs).expect("corrupt jobs dir");
        fs::write(corrupt_jobs.join("33333.json"), "{not json").expect("corrupt record");

        let report = build_deep_cleanup_report(
            &first_compose,
            cache.path(),
            CleanupMode::AllExceptLatest,
            false,
            true,
        )
        .expect("deep report");
        let deep = report.deep.expect("deep section");
        let job_ids = deep
            .orphan_runtime_dirs
            .iter()
            .map(|entry| entry.job_id.as_str())
            .collect::<Vec<_>>();
        assert_eq!(job_ids, vec!["99999"]);
    }

    #[test]
    fn deep_dry_run_does_not_remove_orphan_runtime_dirs() {
        let root = tempdir().expect("root");
        let cache = tempdir().expect("cache");
        let compose = write_compose(root.path(), cache.path());
        let orphan = tracked_paths::enroot_runtime_job_dir(cache.path(), "99999");
        fs::create_dir_all(&orphan).expect("orphan runtime");

        let report = build_deep_cleanup_report(
            &compose,
            cache.path(),
            CleanupMode::AllExceptLatest,
            false,
            true,
        )
        .expect("deep report");
        assert!(orphan.exists());
        assert!(report.deep.expect("deep").orphan_runtime_dirs[0].selected);
    }

    #[test]
    fn run_deep_cleanup_removes_orphan_runtime_dirs() {
        let root = tempdir().expect("root");
        let cache = tempdir().expect("cache");
        let compose = write_compose(root.path(), cache.path());
        let orphan = tracked_paths::enroot_runtime_job_dir(cache.path(), "99999");
        fs::create_dir_all(&orphan).expect("orphan runtime");

        let report = build_deep_cleanup_report(
            &compose,
            cache.path(),
            CleanupMode::AllExceptLatest,
            false,
            false,
        )
        .expect("deep report");
        run_deep_cleanup_report(&report).expect("run deep cleanup");
        assert!(!orphan.exists());
    }
}
