use anyhow::Result;

use crate::planner::ExecutionSpec;
use crate::prepare::{RuntimePlan, RuntimeService};
use crate::spec::ReadinessSpec;

pub fn render_script(plan: &RuntimePlan) -> Result<String> {
    let mut out = String::new();
    out.push_str("#!/bin/bash\n");
    out.push_str(&format!("# Generated by hpc-compose for job {}\n", plan.name));
    out.push_str(&format!("#SBATCH --job-name={}\n", plan.name));
    out.push_str("#SBATCH --nodes=1\n");
    if let Some(partition) = &plan.slurm.partition {
        out.push_str(&format!("#SBATCH --partition={partition}\n"));
    }
    if let Some(account) = &plan.slurm.account {
        out.push_str(&format!("#SBATCH --account={account}\n"));
    }
    if let Some(qos) = &plan.slurm.qos {
        out.push_str(&format!("#SBATCH --qos={qos}\n"));
    }
    if let Some(time) = &plan.slurm.time {
        out.push_str(&format!("#SBATCH --time={time}\n"));
    }
    if let Some(cpus) = plan.slurm.cpus_per_task {
        out.push_str(&format!("#SBATCH --cpus-per-task={cpus}\n"));
    }
    if let Some(mem) = &plan.slurm.mem {
        out.push_str(&format!("#SBATCH --mem={mem}\n"));
    }
    if let Some(gres) = &plan.slurm.gres {
        out.push_str(&format!("#SBATCH --gres={gres}\n"));
    } else if let Some(gpus) = plan.slurm.gpus {
        out.push_str(&format!("#SBATCH --gpus={gpus}\n"));
    }
    if let Some(constraint) = &plan.slurm.constraint {
        out.push_str(&format!("#SBATCH --constraint={constraint}\n"));
    }
    if let Some(output) = &plan.slurm.output {
        out.push_str(&format!("#SBATCH --output={output}\n"));
    }
    if let Some(error) = &plan.slurm.error {
        out.push_str(&format!("#SBATCH --error={error}\n"));
    }
    if let Some(chdir) = &plan.slurm.chdir {
        out.push_str(&format!("#SBATCH --chdir={chdir}\n"));
    }
    for arg in &plan.slurm.submit_args {
        out.push_str(&format!("#SBATCH {arg}\n"));
    }
    out.push_str("\nset -euo pipefail\n\n");
    out.push_str("JOB_TMP=\"${SLURM_SUBMIT_DIR:-$PWD}/.hpc-compose/${SLURM_JOB_ID}\"\n");
    out.push_str("LOG_DIR=\"$JOB_TMP/logs\"\n");
    out.push_str(&format!(
        "CACHE_ROOT={}\n",
        shell_quote(&plan.cache_dir.display().to_string())
    ));
    out.push_str("export ENROOT_CACHE_PATH=\"$CACHE_ROOT/runtime/${SLURM_JOB_ID}/cache\"\n");
    out.push_str("export ENROOT_DATA_PATH=\"$CACHE_ROOT/runtime/${SLURM_JOB_ID}/data\"\n");
    out.push_str("export ENROOT_TEMP_PATH=\"$CACHE_ROOT/runtime/${SLURM_JOB_ID}/tmp\"\n");
    out.push_str("mkdir -p \"$LOG_DIR\" \"$ENROOT_CACHE_PATH\" \"$ENROOT_DATA_PATH\" \"$ENROOT_TEMP_PATH\"\n\n");

    out.push_str("SERVICE_PIDS=()\n");
    out.push_str("SERVICE_NAMES=()\n\n");

    out.push_str("append_unique_mount() {\n");
    out.push_str("  local candidate=$1\n");
    out.push_str("  local existing\n");
    out.push_str("  for existing in \"${PYXIS_MOUNTS[@]:-}\"; do\n");
    out.push_str("    [[ \"$existing\" == \"$candidate\" ]] && return 0\n");
    out.push_str("  done\n");
    out.push_str("  PYXIS_MOUNTS+=(\"$candidate\")\n");
    out.push_str("}\n\n");

    out.push_str("build_pyxis_mounts() {\n");
    out.push_str("  local extra\n");
    out.push_str("  PYXIS_MOUNTS=()\n");
    out.push_str("  if [[ -e /etc/slurm/task_prolog.hk ]]; then\n");
    out.push_str(
        "    append_unique_mount \"/etc/slurm/task_prolog.hk:/etc/slurm/task_prolog.hk\"\n",
    );
    out.push_str(
        "    append_unique_mount \"/etc/slurm/task_prolog.hk:/etc/slurm/task_prolog\"\n",
    );
    out.push_str("  elif [[ -e /etc/slurm/task_prolog ]]; then\n");
    out.push_str("    append_unique_mount \"/etc/slurm/task_prolog:/etc/slurm/task_prolog\"\n");
    out.push_str(
        "    append_unique_mount \"/etc/slurm/task_prolog:/etc/slurm/task_prolog.hk\"\n",
    );
    out.push_str("  fi\n");
    out.push_str("  [[ -d /scratch ]] && append_unique_mount \"/scratch:/scratch\"\n");
    out.push_str("  [[ -e /usr/lib64/slurm/libslurmfull.so ]] && append_unique_mount \"/usr/lib64/slurm/libslurmfull.so\"\n");
    out.push_str("  [[ -e /usr/lib64/libhwloc.so.15 ]] && append_unique_mount \"/usr/lib64/libhwloc.so.15\"\n");
    out.push_str("  for extra in \"$@\"; do\n");
    out.push_str("    append_unique_mount \"$extra\"\n");
    out.push_str("  done\n");
    out.push_str("  local joined=\"\"\n");
    out.push_str("  local item\n");
    out.push_str("  for item in \"${PYXIS_MOUNTS[@]}\"; do\n");
    out.push_str("    if [[ -n \"$joined\" ]]; then\n");
    out.push_str("      joined+=\",\"\n");
    out.push_str("    fi\n");
    out.push_str("    joined+=\"$item\"\n");
    out.push_str("  done\n");
    out.push_str("  printf '%s' \"$joined\"\n");
    out.push_str("}\n\n");

    out.push_str("kill_services() {\n");
    out.push_str("  for pid in \"${SERVICE_PIDS[@]:-}\"; do\n");
    out.push_str("    [[ -z \"$pid\" ]] && continue\n");
    out.push_str("    if kill -0 \"$pid\" 2>/dev/null; then\n");
    out.push_str("      kill \"$pid\" 2>/dev/null || true\n");
    out.push_str("    fi\n");
    out.push_str("  done\n");
    out.push_str("}\n\n");

    out.push_str("cleanup() {\n");
    out.push_str("  local code=$?\n");
    out.push_str("  trap - EXIT INT TERM\n");
    out.push_str("  kill_services\n");
    out.push_str("  wait || true\n");
    out.push_str("  exit \"$code\"\n");
    out.push_str("}\n");
    out.push_str("trap cleanup EXIT INT TERM\n\n");

    out.push_str("wait_for_tcp() {\n");
    out.push_str("  local pid=$1\n");
    out.push_str("  local name=$2\n");
    out.push_str("  local host=$3\n");
    out.push_str("  local port=$4\n");
    out.push_str("  local timeout=${5:-60}\n");
    out.push_str("  local start\n");
    out.push_str("  start=$(date +%s)\n");
    out.push_str("  until bash -lc \"</dev/tcp/${host}/${port}\" >/dev/null 2>&1; do\n");
    out.push_str("    if ! kill -0 \"$pid\" 2>/dev/null; then\n");
    out.push_str("      wait \"$pid\"\n");
    out.push_str(
        "      echo \"Service '$name' exited before ${host}:${port} became reachable\" >&2\n",
    );
    out.push_str("      return 1\n");
    out.push_str("    fi\n");
    out.push_str("    if (( $(date +%s) - start >= timeout )); then\n");
    out.push_str("      echo \"Timed out waiting for ${host}:${port} for service '$name'\" >&2\n");
    out.push_str("      return 1\n");
    out.push_str("    fi\n");
    out.push_str("    sleep 1\n");
    out.push_str("  done\n");
    out.push_str("}\n\n");

    out.push_str("wait_for_log() {\n");
    out.push_str("  local pid=$1\n");
    out.push_str("  local name=$2\n");
    out.push_str("  local logfile=$3\n");
    out.push_str("  local pattern=$4\n");
    out.push_str("  local timeout=${5:-60}\n");
    out.push_str("  local start\n");
    out.push_str("  start=$(date +%s)\n");
    out.push_str("  until grep -E -q \"$pattern\" \"$logfile\" 2>/dev/null; do\n");
    out.push_str("    if ! kill -0 \"$pid\" 2>/dev/null; then\n");
    out.push_str("      wait \"$pid\"\n");
    out.push_str(
        "      echo \"Service '$name' exited before readiness log pattern appeared\" >&2\n",
    );
    out.push_str("      return 1\n");
    out.push_str("    fi\n");
    out.push_str("    if (( $(date +%s) - start >= timeout )); then\n");
    out.push_str(
        "      echo \"Timed out waiting for readiness log pattern for service '$name'\" >&2\n",
    );
    out.push_str("      return 1\n");
    out.push_str("    fi\n");
    out.push_str("    sleep 1\n");
    out.push_str("  done\n");
    out.push_str("}\n\n");

    out.push_str("monitor_services() {\n");
    out.push_str("  while true; do\n");
    out.push_str("    local active=0\n");
    out.push_str("    for i in \"${!SERVICE_PIDS[@]}\"; do\n");
    out.push_str("      local pid=${SERVICE_PIDS[$i]}\n");
    out.push_str("      [[ -z \"$pid\" ]] && continue\n");
    out.push_str("      if kill -0 \"$pid\" 2>/dev/null; then\n");
    out.push_str("        active=$((active + 1))\n");
    out.push_str("        continue\n");
    out.push_str("      fi\n");
    out.push_str("      if wait \"$pid\"; then\n");
    out.push_str("        SERVICE_PIDS[i]=''\n");
    out.push_str("      else\n");
    out.push_str("        local status=$?\n");
    out.push_str(
        "        echo \"Service '${SERVICE_NAMES[$i]}' exited with status $status\" >&2\n",
    );
    out.push_str("        return \"$status\"\n");
    out.push_str("      fi\n");
    out.push_str("    done\n");
    out.push_str("    if (( active == 0 )); then\n");
    out.push_str("      return 0\n");
    out.push_str("    fi\n");
    out.push_str("    sleep 1\n");
    out.push_str("  done\n");
    out.push_str("}\n\n");

    for setup in &plan.slurm.setup {
        out.push_str(setup);
        out.push('\n');
    }
    if !plan.slurm.setup.is_empty() {
        out.push('\n');
    }

    for service in &plan.ordered_services {
        render_service(&mut out, service);
        out.push('\n');
    }

    for service in &plan.ordered_services {
        let fn_name = format!("launch_{}", service_token(&service.name));
        out.push_str(&format!("{fn_name}\n"));
        render_readiness(&mut out, service);
        out.push('\n');
    }

    out.push_str("monitor_services\n");
    Ok(out)
}

fn render_service(out: &mut String, service: &RuntimeService) {
    let service_id = service_token(&service.name);
    let fn_name = format!("launch_{service_id}");
    let command_args = execution_argv(&service.execution, service.working_dir.as_deref());
    let srun_args = build_srun_command(service);
    let service_env = service
        .environment
        .iter()
        .map(|(k, v)| format!("{k}={v}"))
        .collect::<Vec<_>>();

    out.push_str(&format!("{fn_name}() {{\n"));
    out.push_str(&format!(
        "  local logfile=\"$LOG_DIR/{}.log\"\n",
        service_id
    ));
    out.push_str(&format!(
        "  local -a service_mounts={}\n",
        bash_array_literal(&service.volumes)
    ));
    out.push_str(&format!(
        "  local -a srun_cmd={}\n",
        bash_array_literal(&srun_args)
    ));
    out.push_str(&format!(
        "  local -a service_cmd={}\n",
        bash_array_literal(&command_args)
    ));
    out.push_str("  local pyxis_mounts\n");
    out.push_str("  pyxis_mounts=$(build_pyxis_mounts \"${service_mounts[@]}\")\n");
    out.push_str("  srun_cmd+=(--container-image=");
    out.push_str(&shell_quote(&service.runtime_image.display().to_string()));
    out.push_str(")\n");
    out.push_str("  if [[ -n \"$pyxis_mounts\" ]]; then\n");
    out.push_str("    srun_cmd+=(\"--container-mounts=$pyxis_mounts\")\n");
    out.push_str("  fi\n");
    out.push_str("  echo \"Starting service ");
    out.push_str(&service.name);
    out.push_str("\"\n");
    if service.environment.is_empty() {
        out.push_str("  \"${srun_cmd[@]}\" \"${service_cmd[@]}\" >\"$logfile\" 2>&1 &\n");
    } else {
        out.push_str(&format!(
            "  local -a service_env={}\n",
            bash_array_literal(&service_env)
        ));
        out.push_str("  env \"${service_env[@]}\" \"${srun_cmd[@]}\" \"${service_cmd[@]}\" >\"$logfile\" 2>&1 &\n");
    }
    out.push_str("  SERVICE_PIDS+=(\"$!\")\n");
    out.push_str(&format!(
        "  SERVICE_NAMES+=({})\n",
        shell_quote(&service.name)
    ));
    out.push_str("}\n");
}

fn render_readiness(out: &mut String, service: &RuntimeService) {
    let pid_expr = "${SERVICE_PIDS[${#SERVICE_PIDS[@]}-1]}";
    let name_expr = "${SERVICE_NAMES[${#SERVICE_NAMES[@]}-1]}";

    if let Some(readiness) = &service.readiness {
        match readiness {
            ReadinessSpec::Sleep { seconds } => {
                out.push_str(&format!("sleep {seconds}\n"));
            }
            ReadinessSpec::Tcp {
                host,
                port,
                timeout_seconds,
            } => {
                let host = host.as_deref().unwrap_or("127.0.0.1");
                let timeout = timeout_seconds.unwrap_or(60);
                out.push_str(&format!(
                    "wait_for_tcp \"{pid_expr}\" \"{name_expr}\" {} {} {}\n",
                    shell_quote(host),
                    port,
                    timeout
                ));
            }
            ReadinessSpec::Log {
                pattern,
                timeout_seconds,
            } => {
                let timeout = timeout_seconds.unwrap_or(60);
                out.push_str(&format!(
                    "wait_for_log \"{pid_expr}\" \"{name_expr}\" \"$LOG_DIR/{}.log\" {} {}\n",
                    service_token(&service.name),
                    shell_quote(pattern),
                    timeout
                ));
            }
        }
    }
}

fn execution_argv(execution: &ExecutionSpec, working_dir: Option<&str>) -> Vec<String> {
    match (execution, working_dir) {
        (ExecutionSpec::ImageDefault, None) => Vec::new(),
        (ExecutionSpec::Shell(script), None) => {
            vec!["/bin/sh".into(), "-lc".into(), script.clone()]
        }
        (ExecutionSpec::Exec(argv), None) => argv.clone(),
        (ExecutionSpec::Shell(script), Some(dir)) => vec![
            "/bin/sh".into(),
            "-lc".into(),
            "cd \"$1\" && shift && exec /bin/sh -lc \"$1\"".into(),
            "hpc-compose".into(),
            dir.to_string(),
            script.clone(),
        ],
        (ExecutionSpec::Exec(argv), Some(dir)) => {
            let mut wrapped = vec![
                "/bin/sh".into(),
                "-lc".into(),
                "cd \"$1\" && shift && exec \"$@\"".into(),
                "hpc-compose".into(),
                dir.to_string(),
            ];
            wrapped.extend(argv.clone());
            wrapped
        }
        (ExecutionSpec::ImageDefault, Some(_)) => unreachable!("validated earlier"),
    }
}

fn build_srun_command(service: &RuntimeService) -> Vec<String> {
    let mut args = vec![
        "srun".to_string(),
        "--nodes=1".to_string(),
        "--ntasks=1".to_string(),
        "--exact".to_string(),
        "--overlap".to_string(),
    ];
    if matches!(service.execution, ExecutionSpec::ImageDefault) {
        args.push("--container-entrypoint".to_string());
    }
    if !service.environment.is_empty() {
        let env_names = service
            .environment
            .iter()
            .map(|(name, _)| name.as_str())
            .collect::<Vec<_>>()
            .join(",");
        args.push(format!("--container-env={env_names}"));
    }
    if let Some(cpus) = service.slurm.cpus_per_task {
        args.push(format!("--cpus-per-task={cpus}"));
    }
    if let Some(gres) = &service.slurm.gres {
        args.push(format!("--gres={gres}"));
    } else if let Some(gpus) = service.slurm.gpus {
        args.push(format!("--gpus={gpus}"));
    }
    args.extend(service.slurm.extra_srun_args.clone());
    args
}

fn bash_array_literal(items: &[String]) -> String {
    let body = items
        .iter()
        .map(|item| shell_quote(item))
        .collect::<Vec<_>>()
        .join(" ");
    format!("({body})")
}

fn service_token(value: &str) -> String {
    let mut token = String::new();
    for byte in value.bytes() {
        if byte.is_ascii_alphanumeric() {
            token.push(byte as char);
        } else {
            token.push_str(&format!("_x{byte:02x}_"));
        }
    }
    token
}

fn shell_quote(value: &str) -> String {
    if value.is_empty() {
        return "''".to_string();
    }
    let escaped = value.replace('\'', "'\"'\"'");
    format!("'{escaped}'")
}

#[cfg(test)]
mod tests {
    use std::path::PathBuf;

    use super::*;
    use crate::spec::{ReadinessSpec, ServiceSlurmConfig, SlurmConfig};

    fn runtime_service() -> RuntimeService {
        RuntimeService {
            name: "worker".into(),
            runtime_image: PathBuf::from("/shared/cache/worker.sqsh"),
            execution: ExecutionSpec::Exec(vec!["/bin/app".into(), "--port".into(), "8080".into()]),
            environment: vec![("A".into(), "B".into())],
            volumes: vec!["/shared/data:/data".into()],
            working_dir: Some("/workspace".into()),
            readiness: Some(ReadinessSpec::Tcp {
                host: Some("127.0.0.1".into()),
                port: 8080,
                timeout_seconds: Some(20),
            }),
            slurm: ServiceSlurmConfig::default(),
            prepare: None,
            source: crate::planner::ImageSource::LocalSqsh(PathBuf::from(
                "/shared/cache/worker.sqsh",
            )),
        }
    }

    #[test]
    fn exec_form_preserves_argv() {
        let service = runtime_service();
        let argv = execution_argv(&service.execution, service.working_dir.as_deref());
        assert_eq!(argv[0], "/bin/sh");
        assert_eq!(argv[5], "/bin/app");
        assert_eq!(argv[6], "--port");
        assert_eq!(argv[7], "8080");
    }

    #[test]
    fn render_uses_prepared_paths_and_readiness() {
        let plan = RuntimePlan {
            name: "demo".into(),
            cache_dir: PathBuf::from("/shared/cache"),
            slurm: SlurmConfig {
                time: Some("00:10:00".into()),
                ..SlurmConfig::default()
            },
            ordered_services: vec![runtime_service()],
        };
        let script = render_script(&plan).expect("script");
        assert!(script.contains("/shared/cache/worker.sqsh"));
        assert!(script.contains("wait_for_tcp"));
        assert!(script.contains("/bin/app"));
        assert!(script.contains("--container-image='/shared/cache/worker.sqsh'"));
        assert!(script.contains("--container-env=A"));
        assert!(script.contains("build_pyxis_mounts"));
        assert!(script.contains("/scratch:/scratch"));
        assert!(script.contains("/usr/lib64/slurm/libslurmfull.so"));
        assert!(script.contains("/etc/slurm/task_prolog.hk:/etc/slurm/task_prolog"));
    }

    #[test]
    fn shell_form_uses_sh_lc() {
        let argv = execution_argv(&ExecutionSpec::Shell("echo hi".into()), None);
        assert_eq!(argv, vec!["/bin/sh", "-lc", "echo hi"]);
    }

    #[test]
    fn image_default_services_enable_container_entrypoint() {
        let service = RuntimeService {
            name: "redis".into(),
            runtime_image: PathBuf::from("/shared/cache/redis.sqsh"),
            execution: ExecutionSpec::ImageDefault,
            environment: Vec::new(),
            volumes: Vec::new(),
            working_dir: None,
            readiness: None,
            slurm: ServiceSlurmConfig::default(),
            prepare: None,
            source: crate::planner::ImageSource::LocalSqsh(PathBuf::from(
                "/shared/cache/redis.sqsh",
            )),
        };
        let plan = RuntimePlan {
            name: "demo".into(),
            cache_dir: PathBuf::from("/shared/cache"),
            slurm: SlurmConfig::default(),
            ordered_services: vec![service],
        };

        let script = render_script(&plan).expect("script");
        assert!(script.contains("'--container-entrypoint'"));
    }

    #[test]
    fn render_covers_optional_slurm_fields_and_setup_lines() {
        let service = RuntimeService {
            name: "logger".into(),
            runtime_image: PathBuf::from("/shared/cache/logger.sqsh"),
            execution: ExecutionSpec::Shell("echo ready".into()),
            environment: Vec::new(),
            volumes: Vec::new(),
            working_dir: None,
            readiness: Some(ReadinessSpec::Log {
                pattern: "ready".into(),
                timeout_seconds: None,
            }),
            slurm: ServiceSlurmConfig {
                cpus_per_task: Some(3),
                gpus: Some(2),
                gres: None,
                extra_srun_args: vec!["--mpi=none".into()],
            },
            prepare: None,
            source: crate::planner::ImageSource::Remote("docker://redis:7".into()),
        };
        let plan = RuntimePlan {
            name: "demo".into(),
            cache_dir: PathBuf::from("/shared/cache"),
            slurm: SlurmConfig {
                partition: Some("gpu".into()),
                account: Some("proj".into()),
                qos: Some("normal".into()),
                time: Some("01:00:00".into()),
                cpus_per_task: Some(8),
                mem: Some("32G".into()),
                gres: Some("gpu:a100:1".into()),
                constraint: Some("a100".into()),
                output: Some("job.out".into()),
                error: Some("job.err".into()),
                chdir: Some("/work".into()),
                setup: vec!["module load enroot".into()],
                submit_args: vec!["--mail-type=END".into()],
                ..SlurmConfig::default()
            },
            ordered_services: vec![service],
        };
        let script = render_script(&plan).expect("script");
        for expected in [
            "#SBATCH --partition=gpu",
            "#SBATCH --account=proj",
            "#SBATCH --qos=normal",
            "#SBATCH --time=01:00:00",
            "#SBATCH --cpus-per-task=8",
            "#SBATCH --mem=32G",
            "#SBATCH --gres=gpu:a100:1",
            "#SBATCH --constraint=a100",
            "#SBATCH --output=job.out",
            "#SBATCH --error=job.err",
            "#SBATCH --chdir=/work",
            "#SBATCH --mail-type=END",
            "module load enroot",
            "wait_for_log",
            "--mpi=none",
            "--gpus=2",
        ] {
            assert!(script.contains(expected), "missing {expected}");
        }
        let time_pos = script.find("#SBATCH --time=01:00:00").expect("time");
        let strict_pos = script.find("set -euo pipefail").expect("strict mode");
        assert!(time_pos < strict_pos, "SBATCH header must precede shell commands");
    }

    #[test]
    fn readiness_and_argv_helpers_cover_remaining_branches() {
        let mut out = String::new();
        let sleep_service = RuntimeService {
            name: "sleepy".into(),
            runtime_image: PathBuf::from("/tmp/sleepy.sqsh"),
            execution: ExecutionSpec::Shell("echo hi".into()),
            environment: Vec::new(),
            volumes: Vec::new(),
            working_dir: None,
            readiness: Some(ReadinessSpec::Sleep { seconds: 3 }),
            slurm: ServiceSlurmConfig::default(),
            prepare: None,
            source: crate::planner::ImageSource::Remote("docker://redis:7".into()),
        };
        render_readiness(&mut out, &sleep_service);
        assert!(out.contains("sleep 3"));

        let mut out = String::new();
        let tcp_default_service = RuntimeService {
            readiness: Some(ReadinessSpec::Tcp {
                host: None,
                port: 9000,
                timeout_seconds: None,
            }),
            ..sleep_service.clone()
        };
        render_readiness(&mut out, &tcp_default_service);
        assert!(out.contains("'127.0.0.1' 9000 60"));

        assert_eq!(execution_argv(&ExecutionSpec::ImageDefault, None), Vec::<String>::new());
        assert_eq!(
            execution_argv(&ExecutionSpec::Exec(vec!["python".into()]), None),
            vec!["python".to_string()]
        );
        assert_eq!(
            execution_argv(&ExecutionSpec::Shell("echo hi".into()), Some("/work"))[2],
            "cd \"$1\" && shift && exec /bin/sh -lc \"$1\""
        );
    }

    #[test]
    fn build_srun_command_and_string_helpers_cover_remaining_cases() {
        let service = RuntimeService {
            name: "redis/service".into(),
            runtime_image: PathBuf::from("/shared/cache/redis.sqsh"),
            execution: ExecutionSpec::ImageDefault,
            environment: Vec::new(),
            volumes: Vec::new(),
            working_dir: None,
            readiness: None,
            slurm: ServiceSlurmConfig {
                cpus_per_task: Some(2),
                gpus: None,
                gres: Some("gpu:1".into()),
                extra_srun_args: vec!["--exclusive".into()],
            },
            prepare: None,
            source: crate::planner::ImageSource::LocalSqsh(PathBuf::from(
                "/shared/cache/redis.sqsh",
            )),
        };
        let args = build_srun_command(&service);
        assert!(args.contains(&"--container-entrypoint".to_string()));
        assert!(args.contains(&"--cpus-per-task=2".to_string()));
        assert!(args.contains(&"--gres=gpu:1".to_string()));
        assert!(args.contains(&"--exclusive".to_string()));

        assert_eq!(bash_array_literal(&["a".into(), "b c".into()]), "('a' 'b c')");
        assert_eq!(service_token("redis/service"), "redis_x2f_service");
        assert_eq!(service_token("redis_service"), "redis_x5f_service");
        assert_eq!(shell_quote(""), "''");
        assert_eq!(shell_quote("a'b"), "'a'\"'\"'b'");
    }

    #[test]
    fn render_uses_distinct_internal_ids_for_punctuation_variants() {
        let mk_service = |name: &str| RuntimeService {
            name: name.into(),
            runtime_image: PathBuf::from(format!("/shared/cache/{name}.sqsh")),
            execution: ExecutionSpec::Shell("echo hi".into()),
            environment: Vec::new(),
            volumes: Vec::new(),
            working_dir: None,
            readiness: Some(ReadinessSpec::Log {
                pattern: "ready".into(),
                timeout_seconds: Some(5),
            }),
            slurm: ServiceSlurmConfig::default(),
            prepare: None,
            source: crate::planner::ImageSource::Remote("docker://redis:7".into()),
        };
        let plan = RuntimePlan {
            name: "demo".into(),
            cache_dir: PathBuf::from("/shared/cache"),
            slurm: SlurmConfig::default(),
            ordered_services: vec![mk_service("api.v1"), mk_service("api_v1")],
        };

        let script = render_script(&plan).expect("script");
        assert!(script.contains("launch_api_x2e_v1()"));
        assert!(script.contains("launch_api_x5f_v1()"));
        assert!(script.contains("$LOG_DIR/api_x2e_v1.log"));
        assert!(script.contains("$LOG_DIR/api_x5f_v1.log"));
    }

    #[test]
    fn top_level_gpu_branch_and_unreachable_working_dir_guard_are_covered() {
        let plan = RuntimePlan {
            name: "demo".into(),
            cache_dir: PathBuf::from("/shared/cache"),
            slurm: SlurmConfig {
                gpus: Some(4),
                ..SlurmConfig::default()
            },
            ordered_services: vec![RuntimeService {
                name: "svc".into(),
                runtime_image: PathBuf::from("/shared/cache/svc.sqsh"),
                execution: ExecutionSpec::Shell("echo hi".into()),
                environment: Vec::new(),
                volumes: Vec::new(),
                working_dir: None,
                readiness: None,
                slurm: ServiceSlurmConfig::default(),
                prepare: None,
                source: crate::planner::ImageSource::Remote("docker://redis:7".into()),
            }],
        };
        let script = render_script(&plan).expect("script");
        assert!(script.contains("#SBATCH --gpus=4"));

        let panic = std::panic::catch_unwind(|| execution_argv(&ExecutionSpec::ImageDefault, Some("/work")));
        assert!(panic.is_err());
    }
}
